### ISSUE TITLE
ArcGIS Server 10.3

### ISSUE THREAD

**Issue by jgravois** [gisinc/arcgis-level-fixer#4]
after a conversation i had with @jonahadkins at FedGIS, i thought i'd provide an extremely belated followup regarding the behavior of ArcGIS Server 'out of the box'.

based on my understanding of what Jonah was asking, it looks like ArcGIS Server 10.3 behaves as it should (ie: when a Google/Bing tiling scheme is selected, but only a subset of tile levels are cooked, ensure that the indicies of the individual layers present correspond with well known tile level numbers, don't just start counting at zero).

you can see an example [here](http://sampleserver6.arcgisonline.com/arcgis/rest/services/WorldTimeZones/MapServer)

for the JSAPI, its worth a reminder that since LODs are now referenced in the layer metadata which may not be present, this makes it necessary to restrict with a subset [manually](https://developers.arcgis.com/javascript/jssamples/map_switch_layer_on_zoom.html) if you'd like to disable zoom beyond the levels present in your own service.  

let me know if you guys have any other questions.  i'm happy to chat about it more.

**Comment by cbupp** [comment]
Good points @jgravois. ArcGIS tile services are very flexible and do support Google/Bing tiling schemes out-of-the-box. ALF doesn't do anything for services already publish with those schemes.

I'll add further clarification to the README to show that the best coarse of action is use the built-in functionality, and only to rely on ALF if re-publishing isn't an option.
